IHub-173327
ov-integrations/upsource_sync pull request #6
Opened 2021-08-02 05:09 UTC by KupchinskiyVasiliy

2021-08-02 09:12 UTC, asmoiseenko requested changes

2021-08-02 09:12 UTC, asmoiseenko commented on mock/README.md
> +export SERVICE_UN=u_[paste Integration ID here]
can you read the owner of the current dir and use it here?

2021-08-02 09:12 UTC, asmoiseenko commented on mock/README.md
> +## Script mode to install as service (run from `root` user and `mock` directory)
we may proceed with this implementation for now, but looks like this type of mock server will be uniform among other installs. Probably will need a generic script that uses a path to the integration as a parameter and reads integration name, os user name and also finds free port to run a server

2021-08-03 01:53 UTC, KupchinskiyVasiliy commented on mock/README.md
> +export SERVICE_UN=u_[paste Integration ID here]
Yes.

2021-08-03 02:04 UTC, KupchinskiyVasiliy commented on mock/README.md
> +## Script mode to install as service (run from `root` user and `mock` directory)
1) I think no problem if someone write service name to script 1 times.

2) `free port`. Propose to use current variant because some another service which use found port can be stopped and unable to start in future because found port occupated by mock service.

3) Will move this sequence to script.

2021-08-03 05:34 UTC, P4radise submitted a review, later dismissed

2021-08-03 05:56 UTC, KupchinskiyVasiliy commented on mock/README.md
> +export SERVICE_UN=u_[paste Integration ID here]
Done.

2021-08-03 05:57 UTC, KupchinskiyVasiliy commented on mock/README.md
> +## Script mode to install as service (run from `root` user and `mock` directory)
Moved service files to separate directory.

2021-08-03 07:15 UTC, P4radise submitted a review, later dismissed

2021-08-03 07:42 UTC, asmoiseenko requested changes

2021-08-03 07:42 UTC, asmoiseenko commented on mock/daemon/install_as_daemon.sh
> +echo "$SERVICE_NAME will be run on $SERVICE_PORT under $SERVICE_UN user"
"will run on"

2021-08-03 07:42 UTC, asmoiseenko commented on mock/daemon/install_as_daemon.sh
> +# shellcheck source=service_spec.conf
why is it commented?

2021-08-03 07:42 UTC, asmoiseenko commented on mock/daemon/install_as_daemon.sh
> +    echo "### Script for install mock service as daemon ###"
Script **to** install ...

2021-08-03 14:12 UTC, KupchinskiyVasiliy commented on mock/daemon/install_as_daemon.sh
> +# shellcheck source=service_spec.conf
This is "notification" for shellcheck that real source file is service_spec.conf

2021-08-03 14:14 UTC, KupchinskiyVasiliy commented on mock/daemon/install_as_daemon.sh
> +echo "$SERVICE_NAME will be run on $SERVICE_PORT under $SERVICE_UN user"
Done.

2021-08-03 14:14 UTC, KupchinskiyVasiliy commented on mock/daemon/install_as_daemon.sh
> +    echo "### Script for install mock service as daemon ###"
Done.

2021-08-03 15:11 UTC, asmoiseenko approved these changes

2021-08-05 02:14 UTC, P4radise approved these changes

2021-08-05 02:15 UTC, merged