IHub-179826 [Errno 2] No such file or directory: settings.json
ov-integrations/upsource_sync pull request #7
Opened 2021-08-05 07:12 UTC by P4radise

2021-08-05 07:18 UTC, glebowadim requested changes

2021-08-05 07:18 UTC, glebowadim commented on mock/constants.py
> +PATH_TO_SETTINGS_FILE = os.path.abspath('settings.json')
SETTINGS_FILE_PATH

2021-08-05 07:22 UTC, P4radise commented on mock/constants.py
> +PATH_TO_SETTINGS_FILE = os.path.abspath('settings.json')
I decided to leave only the file name in the constants, and moved the path creation to the mock service

2021-08-10 05:25 UTC, glebowadim approved these changes

2021-08-10 05:27 UTC, asmoiseenko approved these changes

2021-08-10 05:28 UTC, merged