IHub-180056 Update settings_schema.json
ov-integrations/upsource_sync pull request #9
Opened 2021-08-11 05:23 UTC by P4radise

2021-08-11 05:42 UTC, asmoiseenko requested changes

2021-08-11 05:42 UTC, asmoiseenko commented on settings_schema.json
> +        "tokenUpsource": {
Mock service uses login and password.

https://github.com/ov-integrations/upsource_sync/blob/master/mock/mock_service.py#L18

2021-08-11 05:42 UTC, asmoiseenko commented on settings_schema.json
> +            "pattern": "^perm:"
I do not think it is a good idea to restrict the token format. Upsource may change it

2021-08-11 05:42 UTC, asmoiseenko commented on settings_schema.json
> +        "tokenUpsource": {
probably support both schemes of authentication - login/password and token?

2021-08-11 05:46 UTC, P4radise commented on settings_schema.json
> +        "tokenUpsource": {
Yes, it supports both authentication formats, but in this case it is only for the versatility of the mock service.
But if needed, I can add both authentication formats to the upsoure integration.

2021-08-11 07:01 UTC, P4radise commented on settings_schema.json
> +            "pattern": "^perm:"
Done

2021-08-11 08:19 UTC, asmoiseenko commented on settings_schema.json
> +        "tokenUpsource": {
don't you see that your integration MUST use token because settings.json to be verified against the schema on integration launch and your mock service consumes the same config file but uses login/password?

How do you think it will work?

2021-08-11 08:20 UTC, asmoiseenko requested changes
https://github.com/ov-integrations/upsource_sync/pull/9/files#r686607831

2021-08-11 09:00 UTC, glebowadim submitted a review, later dismissed

2021-08-11 09:03 UTC, asmoiseenko commented on settings_schema.json
> +        "tokenUpsource": {
ok, now, since schema only supports token auth for the reason to add login/password to the mock service? Remove it from the mock or add to the schema

2021-08-11 09:04 UTC, asmoiseenko requested changes
https://github.com/ov-integrations/upsource_sync/pull/9#discussion_r686641984

2021-08-11 09:06 UTC, P4radise commented on settings_schema.json
> +        "tokenUpsource": {
Since this mock service is the basis for all other mock services, several authentication options have been added to it.
I can't remove that, so fine, I'll put login/password back in the integration.

2021-08-11 15:34 UTC, P4radise commented on settings_schema.json
> +        "tokenUpsource": {
There was some difficulty with the simultaneous support of two authentications. A lot of things need to be redone to make it work correctly, but I don't see the utility of it until the end, so the question is, should it be done?
In integration, I would leave everything as it is. As for mock sercvice - I can remove support for authentication via login/password, and afterwards, when developing mock service for other integrations, and the need for this authentication - I will let you know how to do it.
What do you think?

2021-08-12 06:57 UTC, asmoiseenko requested changes

2021-08-12 06:57 UTC, asmoiseenko commented on settings_schema.json
> +        "tokenUpsource": {
agree

2021-08-16 02:22 UTC, glebowadim approved these changes

2021-08-16 03:47 UTC, asmoiseenko approved these changes

2021-08-16 06:31 UTC, merged